### PR TITLE
Added config setting for making map controls toggleable.

### PR DESCRIPTION
**Pull request by krypto5863**
Not too sure I did it right so you better have a look for yourself before merging.

### CODE REVIEW

**Comment by starstormhun** [comment]
It should default to false regardless of game, since it can also cause issues in KK if the map has multiple lights. With ObjectMap's existence this feature is obsolete, so it should only exist for compatibility reasons. For this same reason it might be worth looking into having it be toggled per scene, since a global setting wouldn't work for everything.

**Comment by starstormhun** [comment]
When loading old scenes, the per-scene setting should be set to on if there's LightSettings maplight data present in the scene, otherwise it should default to off.

**Comment by krypto5863** [comment]
Wouldn't this cause it to load data for every single scene made before since IIRC map data was always saved? If you wanna obsolete it in such a way, might be better to just strip the code and be done with it tbh since in proper cases you're dealing with one light and in improper cases you probably don't want the result.

**Comment by starstormhun** [comment]
It only saves map light data if there's a map selected in the scene. For
those cases it would be possible to compare saved data to what's there by
default to see if any actual modifications were made.
I don't want to completely remove the feature because for cases where
ObjectMap isn't installed that would remove all ability to edit map lights.

**Comment by krypto5863** [comment]
I get where you're coming from but the feature works until it doesn't and your lights are all mangled with no immediate way of fixing it apart from removing the plugin or reloading the map. It's a buggy enough feature that personally I wouldn't want it at all tbh.

Those are my two cents though, if you already have plans you wanna implement, I'll close the PR.

**Comment by starstormhun** [comment]
Hmm yeah, it isn't necessarily worth the time to make a per-scene toggle. If you could change the default to false for both games I'll merge it.

**Comment by krypto5863** [comment]
All done!

**Comment by starstormhun** [comment]
Neat, I'll have to look into another bug soonTM but I'll make a release afterwards.

**Pull request merged**
